# Generated by Django 4.0.5 on 2022-06-19 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="회사명")),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="국가"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="회사 소재지"
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="상세 채용정보"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="포지션"
                    ),
                ),
                (
                    "compensation",
                    models.IntegerField(blank=True, default=0, verbose_name="채용 보상금"),
                ),
                (
                    "technology",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="사용기술"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="마감일"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="jobs.company",
                        verbose_name="회사",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_datetime",),
                "abstract": False,
            },
        ),
    ]
