# Generated by Django 4.0.5 on 2022-06-19 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="applicants",
            field=models.ManyToManyField(
                related_name="applied_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="지원자 목록",
            ),
        ),
    ]
