# Generated by Django 4.0.5 on 2022-06-19 09:54

from django.db import migrations

COMPANY_NAME = "원티드랩"
POST_TITLE_1 = "주니어 개발자 모집"
POST_TITLE_2 = "Node.js 개발자 모집"


def create_sample_instances(apps, schema_editor):
    Company = apps.get_model("jobs", "Company")
    Post = apps.get_model("jobs", "Post")
    db_alias = schema_editor.connection.alias

    company = Company.objects.using(db_alias).create(
        name=COMPANY_NAME, country="한국", region="서울"
    )
    Post.objects.using(db_alias).bulk_create(
        [
            Post(
                company=company,
                title=POST_TITLE_1,
                description="원티드랩에서 백엔드 주니어 개발자를 '적극' 채용합니다. 자격요건은..",
                position="백엔드 주니어 개발자",
                technology="Python",
                compensation=500000,
            ),
            Post(
                company=company,
                title=POST_TITLE_2,
                description="원티드랩에서 백엔드 주니어 개발자를 '적극' 채용합니다. 자격요건은..",
                position="Node.js 개발자",
                technology="Node.js",
                compensation=500000,
            ),
        ]
    )


def destroy_sample_instances(apps, schema_editor):
    Company = apps.get_model("jobs", "Company")
    Post = apps.get_model("jobs", "Post")
    db_alias = schema_editor.connection.alias

    Company.objects.using(db_alias).filter(name=COMPANY_NAME).delete()
    Post.objects.using(db_alias).filter(title=POST_TITLE_1).delete()
    Post.objects.using(db_alias).filter(titme=POST_TITLE_2).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_post_applicants"),
    ]

    operations = [
        migrations.RunPython(create_sample_instances, destroy_sample_instances),
    ]
